backend:
  name: git-gateway
  branch: main

media_folder: static/images
public_folder: ../../static/images/

collections:
 - name: "travel-prackages"
   preview: false
   label: "Travel Packages"
   folder: "content/travel-packages"
   create: true
   slug: "{{slug}}"
   fields:
    - { label: "Location", name: "location", widget: "string" }
    - { label: "Travel Dates", name: "travel-dates", widget: "string" }
    - { label: "Featured Image", name: "featured-image", widget: "image" }
    - { label: "Body", name: "body", widget: "markdown" }

 - name: "banners"
   preview: false
   label: "Banner"
   folder: "content/banner"
   create: true
   slug: "{{slug}}"
   fields:
    - { label: "Sub Title", name: "location", widget: "string" }
    - { label: "Title", name: "travel-dates", widget: "string" }
    - { label: "Featured Image", name: "featured-image", widget: "image" }
    - { label: "Body", name: "body", widget: "markdown" }